[tool.poetry]
name = "skoders"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
transformers = "^4.48.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
